export const companies = [
  {
    id: 1,
    name: "Tech Innovators",
    location: "San Francisco, CA",
    linkedin: "https://www.linkedin.com/company/tech-innovators",
    emails: ["contact@techinnovators.com"],
    phoneNumbers: ["+1 555-1234"],
    comments: "Lead in AI solutions.",
    communicationPeriodicity: 14,
  },
  {
    id: 2,
    name: "Global Enterprises",
    location: "New York, NY",
    linkedin: "https://www.linkedin.com/company/global-enterprises",
    emails: ["info@globalenterprises.com"],
    phoneNumbers: ["+1 555-5678"],
    comments: "Global supplier of enterprise software.",
    communicationPeriodicity: 30,
  },
  {
    id: 3,
    name: "Creative Minds",
    location: "Los Angeles, CA",
    linkedin: "https://www.linkedin.com/company/creative-minds",
    emails: ["hello@creativeminds.com"],
    phoneNumbers: ["+1 555-9876"],
    comments: "Innovating marketing strategies.",
    communicationPeriodicity: 21,
  },
  {
    id: 4,
    name: "Data Solutions",
    location: "Chicago, IL",
    linkedin: "https://www.linkedin.com/company/data-solutions",
    emails: ["support@datasolutions.com"],
    phoneNumbers: ["+1 555-1122"],
    comments: "Providing big data solutions.",
    communicationPeriodicity: 45,
  },
  {
    id: 5,
    name: "Green Technologies",
    location: "Austin, TX",
    linkedin: "https://www.linkedin.com/company/green-technologies",
    emails: ["contact@greentech.com"],
    phoneNumbers: ["+1 555-3344"],
    comments: "Sustainable energy innovations.",
    communicationPeriodicity: 60,
  },
  {
    id: 6,
    name: "Future Enterprises",
    location: "Seattle, WA",
    linkedin: "https://www.linkedin.com/company/future-enterprises",
    emails: ["info@futureenterprises.com"],
    phoneNumbers: ["+1 555-5566"],
    comments: "Pioneers in tech advancements.",
    communicationPeriodicity: 30,
  },
  {
    id: 7,
    name: "Eco Solutions",
    location: "Denver, CO",
    linkedin: "https://www.linkedin.com/company/eco-solutions",
    emails: ["sales@ecosolutions.com"],
    phoneNumbers: ["+1 555-7788"],
    comments: "Eco-friendly product designs.",
    communicationPeriodicity: 90,
  },
  {
    id: 8,
    name: "Cloud Systems",
    location: "San Jose, CA",
    linkedin: "https://www.linkedin.com/company/cloud-systems",
    emails: ["contact@cloudsystems.com"],
    phoneNumbers: ["+1 555-9911"],
    comments: "Cloud computing services.",
    communicationPeriodicity: 15,
  },
  {
    id: 9,
    name: "Cyber Defense Corp.",
    location: "Washington, D.C.",
    linkedin: "https://www.linkedin.com/company/cyber-defense-corp",
    emails: ["support@cyberdefense.com"],
    phoneNumbers: ["+1 555-2233"],
    comments: "Cybersecurity solutions for enterprises.",
    communicationPeriodicity: 30,
  },
  {
    id: 10,
    name: "HealthTech Innovators",
    location: "Boston, MA",
    linkedin: "https://www.linkedin.com/company/healthtech-innovators",
    emails: ["info@healthtechinnovators.com"],
    phoneNumbers: ["+1 555-4455"],
    comments: "Transforming healthcare with technology.",
    communicationPeriodicity: 60,
  },
  {
    id: 11,
    name: "NextGen Robotics",
    location: "San Diego, CA",
    linkedin: "https://www.linkedin.com/company/nextgen-robotics",
    emails: ["support@nextgenrobotics.com"],
    phoneNumbers: ["+1 555-6677"],
    comments: "Leading innovations in robotics.",
    communicationPeriodicity: 30,
  },
  {
    id: 12,
    name: "Digital Visionaries",
    location: "Miami, FL",
    linkedin: "https://www.linkedin.com/company/digital-visionaries",
    emails: ["contact@digitalvisionaries.com"],
    phoneNumbers: ["+1 555-8899"],
    comments: "Digital transformation consulting.",
    communicationPeriodicity: 14,
  },
  {
    id: 13,
    name: "Smart Solutions",
    location: "Dallas, TX",
    linkedin: "https://www.linkedin.com/company/smart-solutions",
    emails: ["hello@smartsolutions.com"],
    phoneNumbers: ["+1 555-1010"],
    comments: "Smart tech for smart businesses.",
    communicationPeriodicity: 30,
  },
  {
    id: 14,
    name: "Innovation Labs",
    location: "Atlanta, GA",
    linkedin: "https://www.linkedin.com/company/innovation-labs",
    emails: ["info@innovationlabs.com"],
    phoneNumbers: ["+1 555-2323"],
    comments: "R&D for next-gen technologies.",
    communicationPeriodicity: 90,
  },
  {
    id: 15,
    name: "Advanced Systems",
    location: "Detroit, MI",
    linkedin: "https://www.linkedin.com/company/advanced-systems",
    emails: ["contact@advancedsystems.com"],
    phoneNumbers: ["+1 555-4343"],
    comments: "Building future tech systems.",
    communicationPeriodicity: 45,
  },
  {
    id: 16,
    name: "AI Pioneers",
    location: "Los Angeles, CA",
    linkedin: "https://www.linkedin.com/company/ai-pioneers",
    emails: ["support@aipioneers.com"],
    phoneNumbers: ["+1 555-5656"],
    comments: "AI solutions for the future.",
    communicationPeriodicity: 60,
  },
  {
    id: 17,
    name: "Quantum Innovations",
    location: "Boston, MA",
    linkedin: "https://www.linkedin.com/company/quantum-innovations",
    emails: ["contact@quantuminnovations.com"],
    phoneNumbers: ["+1 555-7878"],
    comments: "Cutting-edge quantum computing.",
    communicationPeriodicity: 14,
  },
  {
    id: 18,
    name: "CyberTech Solutions",
    location: "New York, NY",
    linkedin: "https://www.linkedin.com/company/cybertech-solutions",
    emails: ["info@cybertechsolutions.com"],
    phoneNumbers: ["+1 555-9999"],
    comments: "Cybersecurity for the modern world.",
    communicationPeriodicity: 30,
  },
  {
    id: 19,
    name: "Sustainable Tech",
    location: "Denver, CO",
    linkedin: "https://www.linkedin.com/company/sustainable-tech",
    emails: ["contact@sustainabletech.com"],
    phoneNumbers: ["+1 555-1212"],
    comments: "Sustainable technology solutions.",
    communicationPeriodicity: 45,
  },
  {
    id: 20,
    name: "Cloud Innovations",
    location: "San Francisco, CA",
    linkedin: "https://www.linkedin.com/company/cloud-innovations",
    emails: ["support@cloudinnovations.com"],
    phoneNumbers: ["+1 555-3434"],
    comments: "Innovative cloud computing solutions.",
    communicationPeriodicity: 30,
  }
];
